### ISSUE TITLE
duelPlayerParam - Awaken models

### ISSUE THREAD

**Issue by Vampironl** [TheLeonX/NSC-Toolbox#1]
I added a new costume for a character that also has a separate awaken model (transformation)
Every time I wanted to awake the character in the new costume the game closed in error. 

After inspecting the duelPlayerParam  I noticed the awaken model entry was gone after compiling. 
Im pretty sure there is a bug in the tool which makes the awaken models are not compiling. 
![Aw](https://github.com/TheLeonX/NSC-Toolbox/assets/161167912/e2392591-3303-480a-a43a-d0858b9db542)

Edit : Sorry for putting it with the wrong tool. Bug report should have been with the ModTool

**Comment by TheLeonX** [comment]
I will check it tomorrow
