### ISSUE TITLE
duelPlayerParam - Awaken models 

### ISSUE THREAD

**Issue by Vampironl** [TheLeonX/NSC-Toolbox#3]
Unfortunatly the previous update didn't solve the problem. When I compile the mod it still "deletes" the awake costume from the list. 

Here is an example, I added a new costume in slot 10 with a corrosponding costume in slot 10 for the awake : 
![1](https://github.com/TheLeonX/NSC-Toolbox/assets/161167912/23161517-e9cd-4ef5-8f5f-57d861e60364)

After compiling it moved the costume to slot 4, guess this is on purpose since this is the first available slot. However it didn't take the awaken costume as slot 4 of awaken is empty. 
![2](https://github.com/TheLeonX/NSC-Toolbox/assets/161167912/c341f7c8-2cb6-448d-ad15-535d938f15ed)

I doublechecked slot 10 to see if maybe it remained over there but also this one is empty.
![3](https://github.com/TheLeonX/NSC-Toolbox/assets/161167912/1a94f796-770b-4b89-aed1-1189c9661baa)

**Comment by TheLeonX** [comment]
![image](https://github.com/TheLeonX/NSC-Toolbox/assets/92672927/6fde9e2e-8308-4232-a413-86a71c3c0344)
in my case it worked.
How exactly you export mod with toolbox?
Send your mod there if you want more details. What you use for export and exported.

**Comment by Vampironl** [comment]
Normally I delete all existing costumes from the duelPlayerParam, don't know why I do exactly but it looks more "clean" to me. 
So I end up with only 2 costumes in the duelPlayerParam file, once for the normal costume and once for the awaken. Both in slot 10.

The HEX looks like this before I compile : 
![4](https://github.com/TheLeonX/NSC-Toolbox/assets/161167912/9af64f0b-c706-47db-8e5c-cc6f9826b0a2)

Let me try it without deleting the "original" costumes.

**Comment by TheLeonX** [comment]
Im genuinely confused about that part cuz mod manager doesnt use duelPlayerParam for setting models. Why in your case you have it with only one 2kzu entry?

**Comment by Vampironl** [comment]
> Im genuinely confused about that part cuz mod manager doesnt use duelPlayerParam for setting models. Why in your case you have it with only one 2kzu entry?

I assumed modmanager moves all costumes to the first available slot, as it moved from slot 10 (before compile) to slot 4 (after compile).

I have only one costume because I always "delete" all others since they will be added again by the game originals. I only fill the duelPlayerParam file with the costume I'm adding. 

I will try it without deleting the existing costumes, and add the new costume to slot 4 to see what it does then. 

EDIT : 
I tried again with all the costumes as they are in the game original but same result. This is before compiling : 
![Input](https://github.com/TheLeonX/NSC-Toolbox/assets/161167912/d5f66e4e-10e6-4a13-8cc6-01de593cee93)

After compiling I checked the duelPlayerParam again (in the CPK ofcourse, that the moddingTool generates) and the costume is no longer there : 
![Output](https://github.com/TheLeonX/NSC-Toolbox/assets/161167912/ec04b7b3-f33a-4d7c-b076-59b4d5d57ba0)

**Comment by TheLeonX** [comment]
Send mod here, in data_win32 and what you got in .nsc

**Comment by Vampironl** [comment]
I added the mod itself (extra costume for kakuzo, 2kzu), in this mod itself the duelPlayerParam is alright (with 4th costume for awaken).

I also added the CPK the ModTool generates, if you check the duelPlayerParam  in the CPK then the 4th entry is gone. 
[Mods.zip](https://github.com/TheLeonX/NSC-Toolbox/files/14963255/Mods.zip)
[param_files.zip](https://github.com/TheLeonX/NSC-Toolbox/files/14963263/param_files.zip)

**Comment by TheLeonX** [comment]
What version of toolbox you using for exporting. As i told, mod manager doesnt use duelPlayerParam for param files.
In your case i see that you added it manually, but mod manager doesnt use it for adding models.
![image](https://github.com/TheLeonX/NSC-Toolbox/assets/92672927/aeafd9fd-7486-448f-b80c-4b80cf9fc87a)
All info comes from config file

**Comment by TheLeonX** [comment]
In your mod AwakeModel is empty, but i literally cant tell you why if you edit this .nsc manually.
All you had to do is just add model and icons in param files for data_win32, and then export it with toolbox. You dont need to edit .nsc file if you added model properly with data_win32 method

**Comment by Vampironl** [comment]
Ahh I guess thats the problem!! 

Indeed I didn't add it in the config file. I wasn't aware it took the costume name from there instead of from the duelPlayerParam  file. It also makes sense now what you said before.

Oh dear, guess my stupidity took a lot of your time. Guess I still have to learn a lot (even though I managed to create a lot of mods already with this tool)

sorry for wasting so much precious time!
