### ISSUE TITLE
4nrt2hntprm_load.bin.xfbin causing crash

### ISSUE THREAD

**Issue by MoeruStorm** [TheLeonX/NSC-Toolbox#4]
### Bug
When opening 4nrt2hntprm_load.bin.xfbin with Toolbox version 1.4.0.0 Toolbox's Character File Loader Editor, it will attempt to open it for a few seconds then crash the entire program. The file is from v1.01 of the game, I'm unsure whether or not it's been updated in v1.40.

### Can it be reproduced?
Yes, 100% of the time.

[4nrt2hntprm_load.bin.xfbin.zip](https://github.com/user-attachments/files/16478913/4nrt2hntprm_load.bin.xfbin.zip)

**Comment by TheLeonX** [comment]
This file is leftover from Revolution. It wasnt used in Storm Connections somehow.
